# environment.yaml
name: mash_settings_p312
dependencies:
  - python>=3.12.0
  - pip
  - pip:
    - pytest
    - pytest_check
    - radon
    - coverage
    - hatch
    # - pathlib
    # - pandas
    # - polars
    - pydantic>=2
    - pydantic-settings
    # - pyarrow
    # - boltons
    # - paramiko
    # - gnupg
    # - minio
    # - boto3
    - universal_pathlib
    # - smart_open[s3]
    # - paramiko
    # - python-gnupg
    # - xsdata
    #This package
    - -e .
    #Other Mountain Ash Packages
    # - -e ../mountainash-constants
    #- -e ../mountainash-settings
    #- -e ../mountainash-auth-settings
    # - -e ../mountainash-utils
    # - -e ../mountainash-utils-dataclasses
    # - -e ../mountainash-utils-dataframes


