[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mountainash_settings"
dynamic = ["version"]
description = 'Mountain Ash - Settings'
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Nathaniel Ramm", email = "nathaniel.ramm@discretedatascience.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "pydantic>=2",
  "pydantic-settings",
  "universal_pathlib"
]

[project.urls]
Documentation = "https://github.com/mountainash-io/mountainash-settings#readme"
Issues = "https://github.com/mountainash-io/mountainash-settings/issues"
Source = "https://github.com/mountainash-io/mountainash-settings"


[tool.hatch.version]
path = "src/mountainash_settings/__version__.py"

# Pytest and Test Coverage
[[tool.hatch.envs.test.matrix]]
python = ["3.11", "3.12",  "3.10" ] # "3.8", "3.9","3.9",

[tool.hatch.envs.test]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
  "pytest_check",
]
[tool.hatch.envs.test.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "test-cov",
  "cov-report",
]

# Radon Complexity Checks
[tool.hatch.envs.radon]
dependencies = [
  "radon",
]
[tool.hatch.envs.radon.scripts]
radon-cc = "radon cc . -nd"
radon-mi = "radon mi . -nd"

# Mypy Type checks
[tool.hatch.envs.types]
dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/mountainash_settings tests}"

# Downstream package testing
[tool.hatch.envs.test_downstream]
dependencies = [  
  "pytest",
  "pytest_check",
  "mountainash_auth_settings @ {root:uri}/../mountainash-auth-settings",
  "mountainash_acrds_settings @ {root:uri}/../mountainash-acrds-settings",
  "mountainash_constants @ {root:uri}/../mountainash-constants",
  "mountainash_acrds_constants @ {root:uri}/../mountainash-acrds-constants",
  "mountainash_utils_dataclasses @ {root:uri}/../mountainash-utils-dataclasses"
  ]

[tool.hatch.envs.test_downstream.scripts]
test = [#"pytest {args:tests}", 
        "pytest ../mountainash-auth-settings"
]

# Downstream ACRDS package testing
[tool.hatch.envs.test_downstream_acrds]
dependencies = [  
  "pytest",
  "pytest_check",
  "mountainash_constants @ {root:uri}/../mountainash-constants",
  "mountainash_acrds_settings @ {root:uri}/../mountainash-acrds-settings",
  "mountainash_acrds_constants @ {root:uri}/../mountainash-acrds-constants",
  "mountainash_utils_dataclasses @ {root:uri}/../mountainash-utils-dataclasses",
  "mountainash_utils @ {root:uri}/../mountainash-utils"
  ]

[tool.hatch.envs.test_downstream_acrds.scripts]
test = ["pytest ../mountainash-acrds-settings"]


# Coverage Parameters
[tool.coverage.run]
source_pkgs = ["mountainash_settings", "tests"]
branch = true
parallel = true
omit = [
  "src/mountainash_settings/__version__.py",
]

[tool.coverage.paths]
mountainash_settings = ["src/mountainash_settings", "*/mountainash-settings/src/mountainash_settings"]
tests = ["tests", "*/mountainash-settings/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__:",
  "if TYPE_CHECKING:",
]

[tool.hatch.build.targets.wheel]
packages = ["src/mountainash_settings"]