sonar.projectKey=mountainash-io_mountainash-settings
sonar.organization=mountainash-io
 
# sonar.python.coverage.reportPaths=coverage.xml

# Define separate root directories for sources and tests
sonar.sources = ./src/
sonar.tests = ./tests/