"""Private selected native operations, not a public filesystem abstraction."""
from __future__ import annotations

import importlib
import sys
from pathlib import Path
from typing import Protocol, cast

from .errors import _Failure


class NativeOps(Protocol):
    def open_root(self, path: Path) -> int: ...
    def open_namespace(self, parent: int, name: str, *, create: bool) -> int: ...
    def open_file(self, parent: int, name: str, *, writable: bool = False) -> int: ...
    def create_file(self, parent: int, name: str) -> int: ...
    def read_file(self, handle: int) -> bytes: ...
    def write_file(self, handle: int, payload: bytes) -> None: ...
    def check_entry(self, parent: int, name: str, handle: int) -> None: ...
    def replace_file(
        self, parent: int, temp_name: str, temp_handle: int, destination: str,
    ) -> None: ...
    def cleanup_owned(self, parent: int, name: str, handle: int) -> None: ...
    def lock(self, handle: int, *, blocking: bool = True) -> bool: ...
    def unlock(self, handle: int) -> None: ...
    def close(self, handle: int) -> None: ...
    def reason(self, exc: Exception) -> str: ...


def select_ops() -> NativeOps:
    if sys.platform in ("linux", "darwin"):
        module = "._native_posix"
    elif sys.platform == "win32":
        module = "._native_windows"
    else:
        raise _Failure("unsupported_filesystem")
    try:
        return cast(NativeOps, importlib.import_module(module, __package__))
    except (ImportError, AttributeError, OSError):
        raise _Failure("unsupported_filesystem") from None
