name: Pytest Runner

on: 
  push:
    paths:
      - 'src/mountainash_settings/**'    
  workflow_dispatch:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ "3.12"] #, "3.8", "3.9", "3.10","3.11",]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install hatch

      - name: Create virtual environment
        run: hatch env create test

      - name: Run tests
        run: hatch run test:test

  complexity-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Hatch
        run: pip install hatch

      - name: Create virtual environment
        run: hatch env create radon

      - name: Complexity checks with radon - cc
        run: hatch run radon:radon-cc

      - name: Complexity checks with radon - mi
        run: hatch run radon:radon-mi

  linting-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Hatch
        run: pip install hatch

      - name: Create virtual environment
        run: hatch env create ruff

      - name: Linting checks with ruff
        run: hatch run ruff:check

      