# name: Coverage

# on: 
#   push:
#     paths:
#       - 'src/mountainash_settings/**'    
#   workflow_dispatch:

# jobs:

#   coverage-checks:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python 3.12
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"
          
#       - name: Install Hatch
#         run: pip install hatch

#       - name: Create virtual environment
#         run: hatch env create test_github

#       - name: Run Coverage Tests
#         run: hatch run test_github:cov

#       - name: Upload coverage reports to Codecov
#         uses: codecov/codecov-action@v4.0.1
#         with:
#           token: ${{ secrets.CODECOV_TOKEN }}
#           slug: mountainash-io/mountainash-settings
      