name: Pytest

on: 
  push:
    paths:
      - 'src/mountainash_settings/**'    
  pull_request:
    paths:
      - 'src/mountainash_settings/**'          
  workflow_dispatch:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ "3.12"] #, "3.8", "3.9", "3.10","3.11",]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }} 

      # Install Hatch
      - name: Install Hatch
        run: pip install hatch

      - name: Create virtual environment
        run: hatch env create test_github

      #Run Pytest
      - name: Run tests
        run: hatch run test_github:test

      # Run Coverage
      - name: Run Coverage Tests
        run: hatch run test_github:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: mountainash-io/mountainash-settings